### ISSUE TITLE
Building Bridges: Seamlessly Connecting the Backend Symphony to Frontend Harmony

### ISSUE THREAD

**Issue by 0mBudsMan** [opencodeiiita/Scoop-Frontend#93]
# Task: Implement Redux Toolkit for Signup and Signin

### Goal
Implement Redux Toolkit for managing state in the registration and signin forms of the project. Create actions, reducers, constants, and a store for handling signup and signin functionalities.

**- Make a seperate folder for action, a seperate folder for constants, a seperate folder for reducers and a store.js file.**

### Tasks

1. **Setup Redux Toolkit**
   - Integrate Redux Toolkit into the project.

2. **Define Actions, Reducers, and Constants**
   - Create actions, reducers, and constants specifically for signup and signin functionalities.
   - For signup, define actions like `SIGNUP_REQUEST`, `SIGNUP_SUCCESS`, `SIGNUP_FAIL`, 'SIGNUP_RESET'.
   - For signin, define actions like `SIGNIN_REQUEST`, `SIGNIN_SUCCESS`, `SIGNIN_FAIL`, 'SIGNIN_RESET.

3. **Integrate Actions and Reducers in the Store**
   - Configure the Redux store and include the newly created actions and reducers.

4. **Use Axios for API Requests**
   - Utilize Axios to make API requests for both signup and signin operations.
   - The backend is available in the following repository: [Link to Backend Repository](https://github.com/opencodeiiita/Scoop-Backend).

5. **Functional Registration and Signin Forms**
   - Ensure that the registration and signin forms are connected to the Redux store.
   - Implement functionality for signup and signin forms to interact with the Redux state.
   - The state should also tell whether user is signed in or not. If a user is not signed in, instead of displaying <Home /> component in homepage, redirect to route of sign up form (/register).

### Additional Information
- The backend for the project is present in the following repository: [Link to Backend Repository](https://github.com/opencodeiiita/Scoop-Backend)
- Make sure to handle success and error scenarios appropriately, dispatching actions based on the API responses.
**- Implement necessary toast notifications for user feedback.**

## Deadline
Please submit your pull request by [36 hours].

**Note:** Feel free to ask for any clarifications or assistance during the implementation process.
Backend routes: /api/auth/register
/api/auth/login
Frontend routes: /signin 
/register

- [ ] Set up redux
- [ ] Use axios to fetch 
- [ ] React toast for message displaying

**Comment by rnavaneeth992** [comment]
claim

**Comment by 0mBudsMan** [comment]
@rnavaneeth992 kindly read the issue and let me know if you need any clarifications. Kindly make a pr by 36 hours

**Comment by rnavaneeth992** [comment]
> @rnavaneeth992 kindly read the issue and let me know if you need any clarifications. Kindly make a pr by 36 hours

Sure

**Comment by WadadParker** [comment]
Claim

**Comment by 0mBudsMan** [comment]
@rnavaneeth992 status?

**Comment by rnavaneeth992** [comment]
@0mBudsMan Completed 

Already made PR, Told some changes doing it

**Comment by rnavaneeth992** [comment]
> @rnavaneeth992 status?

Hi I will complete by Trm for sure

**Comment by rnavaneeth992** [comment]
@0mBudsMan I am new to it and I though of learn and do it

But I think I can't do this task by trm due to sudden personal work 
I will learn asap and from next backend and frontend integration I will do it 

Sorry for this
Unassign me the task

**Comment by Rohit-110** [comment]
@0mBudsMan  claim

**Comment by kushal7201** [comment]
Claim

**Comment by chiragmalik2612** [comment]
c

**Comment by Apoorv012** [comment]
claim

**Comment by Rohit-110** [comment]
claim

**Comment by chiragmalik2612** [comment]
@0mBudsMan assign me this issue ....commented first

**Comment by 0mBudsMan** [comment]
@chiragmalik2612 
Apologies Chirag, only the comments added after unassigning the issue to previous assignee will be taken in queue!

**Comment by 0mBudsMan** [comment]
@Apoorv012 kindly contact for any help and watch for time limit!

**Comment by 0mBudsMan** [comment]
@Apoorv012 https://www.youtube.com/watch?v=0W6i5LYKCSI&ab_channel=DipeshMalvia
https://www.youtube.com/watch?v=2JBx_06dD1k&ab_channel=PiyushGarg
https://www.youtube.com/watch?v=zrs7u6bdbUw&t=4509s&ab_channel=freeCodeCamp.org
